export const GET_CHARACTERS = "GET_CHARACTERS";
export const ADD_CHARACTER_TO_FAVORITE = "ADD_CHARACTER_TO_FAVORITE";
export const REMOVE_CHARACTER_FROM_FAVORITE = "REMOVE_CHARACTER_FROM_FAVORITE";
export const SEARCH_CHARACTER = "SEARCH_CHARACTER";
export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
